author: 晋恒温
title: 8 at My House
url: http://8atmyhouse.com
permalink: /blog/:title.html
paginate: 5
paginate_path: /page/:num
safe: true
markdown: redcarpet
exclude: ['Gemfile', 'Gemfile.lock']
duoshuo: lihuazhang

